### PR TITLE
HQ-692 Merge security repository into integration

### PR DESCRIPTION
**Pull request by danpoltawski**
[Creating this pull request for david so I can comment on it)

### CODE REVIEW

**Comment by danpoltawski** [comment]
@dmonllao IMO I would not add the security remote, I would just do a pull with the remote url  - I feel like having it defined gives the possibile risk of an accidental push..

**Comment by danpoltawski** [comment]
Note that there are more things that would be nice to be covered by this script, mentioned in the [(HQ restricted) doc](https://docs.google.com/document/d/1DTCjWj7fh3TZupCva0kgAgHeNEqDHxcxF_rYdq92VUc/edit#heading=h.ykayk1msbd02)

**Comment by dmonllao** [comment]
Ok, I've updated and tested the automated merge from security, ready to be applied when we decide to switch to "AS"

**Comment by dmonllao** [comment]
Note that this pull request depends on https://gist.github.com/dmonllao/069d3c8248607f4de124 and https://gist.github.com/dmonllao/f3c4550cd14fb112898b being applied to integrators' clones that are used to push to security.git

**Comment by dmonllao** [comment]
If we decide that we don't want MS to prepend all security patches (we would protect security issues from being pushed to public repos by other means like mdk or separate dirs) I will need to update this patch to avoid rewording the security commits messages as they will already come ready to be merged.

**Comment by dmonllao** [comment]
Updated patch to get rid of the ^MSMDL - ^MDL renaming thing and the security- prefix for the security.git repo branches.

**Comment by stronk7** [comment]
Hi,

I am going to close this now. After some discussion it has been agreed that the current approach, moving issues from security to integration a couple of days before the release is working ok and gives us the opportunity to test and detect any potential problem.

Ciao :-)

**Pull request closed without merging**
