### PR TITLE
Upgrade notes rewrite

### PR DESCRIPTION
**Pull request by andrewnicols**
This is a fairly comprehensive rewrite of the version.php handling in the release tool.

I've added copious amounts of unit tests which cover most situations.

In order to correctly generate the upgrade notes we need to specify the version that we will be generating for. To do that we need to determine what the next version is easily, without bumping the version immediately.

The easiest way to do so is to specify the target version as an argument to the upgrade notes tooling.

This set of changes completely refactors the `bumpversions.php` file to break out the reading, writing, and checking, into Helper and VersionInfo classes which are themselves thoroughly unit tested.

Note: This also adds support for Moodle 4.3 => Moodle 5.0 transitions.

### CODE REVIEW

**Review by junpataleta — CHANGES_REQUESTED** [review]
Thanks, @andrewnicols. Great stuff working on these changes! Well done!

I think this is almost ready.

Just noticed some minor things...

#### Readme

We need to update the readme file about the requirements (PHP 8.2+ and running `composer install`)

#### Unit test

There are some calls to `assertNull()` for methods with `void` return. Although they're passing, I'm not sure if it's appropriate.

- [HelperTest::testRequireBranchNameValid()](https://github.com/moodlehq/mdlrelease/pull/99/files#diff-731cb8fc385b3cdcc613774822672c7f822e3e85f89867b24651b405f89d22e5R158)
- [HelperTest::testRequirePathValid()](https://github.com/moodlehq/mdlrelease/pull/99/files#diff-731cb8fc385b3cdcc613774822672c7f822e3e85f89867b24651b405f89d22e5R237)
- [HelperTest::testRequireVersionFileValid()](https://github.com/moodlehq/mdlrelease/pull/99/files#diff-731cb8fc385b3cdcc613774822672c7f822e3e85f89867b24651b405f89d22e5R283)

#### Existing issue

Possibly as a separate issue, this might also be a good opportunity to improve/fix the `--type rc` release. I noticed that (even before this PR) if a number is not provided, the release script does not seem to recognise that it's an RC release type and performs a major version release type, leading to the following output.

```bash
Starting pre-release processing for rc release.
...
Pre-release processing has been completed.

Changes can be reviewed using the --show option.

Please propagate these changes to the integration repository with the following:

  git push origin main
  
  git tag -a 'v4.5.0' -m 'MOODLE_405' 23d349419204162f9fd280d702f11bd5021696a6

Once CI jobs have ended successfully, you can safely push the release tag(s) to the integration repository:

  git push origin --tags
```

We could either do the following:

- Option 1: Exit with an error message that the RC number is required
- Option 2: The RC number will fall back to 1 if a number is not supplied

We'd probably need to validate the supplied RC number to ensure we avoid errors.

But yeah, I think we can just fix this on a separate issue. So, I'll leave it up to you.

**Comment by andrewnicols** [comment]
> #### Readme
> We need to update the readme file about the requirements (PHP 8.2+ and running `composer install`)

Updated to add the composer command. I've also amended the lock file to support PHP 8.1 too.

> #### Unit test
> There are some calls to `assertNull()` for methods with `void` return. Although they're passing, I'm not sure if it's appropriate.
> 
> * [HelperTest::testRequireBranchNameValid()](https://github.com/moodlehq/mdlrelease/pull/99/files#diff-731cb8fc385b3cdcc613774822672c7f822e3e85f89867b24651b405f89d22e5R158)
> * [HelperTest::testRequirePathValid()](https://github.com/moodlehq/mdlrelease/pull/99/files#diff-731cb8fc385b3cdcc613774822672c7f822e3e85f89867b24651b405f89d22e5R237)
> * [HelperTest::testRequireVersionFileValid()](https://github.com/moodlehq/mdlrelease/pull/99/files#diff-731cb8fc385b3cdcc613774822672c7f822e3e85f89867b24651b405f89d22e5R283)

I considered this when I wrote them and decided that this was currently the least worst evil.

These methods either throw an exception or return void. I _could_ make them return `true`, but that isn't available until PHP 8.2.

I've changed the return val to bool. We can change it to true later.

> #### Existing issue

Let's raise an issue for that and fix it later. We should be basing a lot of these transitions on the current value and either erroring or warning on invalid results already.

**Comment by andrewnicols** [comment]
Pinging @junpataleta

**Review by junpataleta — APPROVED** [review]
Awesome work, @andrewnicols ! I think this is good to go!

**Pull request merged**
